apiVersion: v1
kind: PersistentVolume
metadata:
  name: dolibarr-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  emptyDir: {}
